//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deceased2010Client.Deceased2010Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Deceased2010Service.Deceased2010ServiceSoap")]
    public interface Deceased2010ServiceSoap {
        
        // CODEGEN: Generating message contract since element name dateinput from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNamesByDate", ReplyAction="*")]
        Deceased2010Client.Deceased2010Service.GetNamesByDateResponse GetNamesByDate(Deceased2010Client.Deceased2010Service.GetNamesByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNamesByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<Deceased2010Client.Deceased2010Service.GetNamesByDateResponse> GetNamesByDateAsync(Deceased2010Client.Deceased2010Service.GetNamesByDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNamesByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNamesByDate", Namespace="http://tempuri.org/", Order=0)]
        public Deceased2010Client.Deceased2010Service.GetNamesByDateRequestBody Body;
        
        public GetNamesByDateRequest() {
        }
        
        public GetNamesByDateRequest(Deceased2010Client.Deceased2010Service.GetNamesByDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNamesByDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dateinput;
        
        public GetNamesByDateRequestBody() {
        }
        
        public GetNamesByDateRequestBody(string dateinput) {
            this.dateinput = dateinput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNamesByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNamesByDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Deceased2010Client.Deceased2010Service.GetNamesByDateResponseBody Body;
        
        public GetNamesByDateResponse() {
        }
        
        public GetNamesByDateResponse(Deceased2010Client.Deceased2010Service.GetNamesByDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNamesByDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNamesByDateResult;
        
        public GetNamesByDateResponseBody() {
        }
        
        public GetNamesByDateResponseBody(string GetNamesByDateResult) {
            this.GetNamesByDateResult = GetNamesByDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Deceased2010ServiceSoapChannel : Deceased2010Client.Deceased2010Service.Deceased2010ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Deceased2010ServiceSoapClient : System.ServiceModel.ClientBase<Deceased2010Client.Deceased2010Service.Deceased2010ServiceSoap>, Deceased2010Client.Deceased2010Service.Deceased2010ServiceSoap {
        
        public Deceased2010ServiceSoapClient() {
        }
        
        public Deceased2010ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Deceased2010ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Deceased2010ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Deceased2010ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Deceased2010Client.Deceased2010Service.GetNamesByDateResponse Deceased2010Client.Deceased2010Service.Deceased2010ServiceSoap.GetNamesByDate(Deceased2010Client.Deceased2010Service.GetNamesByDateRequest request) {
            return base.Channel.GetNamesByDate(request);
        }
        
        public string GetNamesByDate(string dateinput) {
            Deceased2010Client.Deceased2010Service.GetNamesByDateRequest inValue = new Deceased2010Client.Deceased2010Service.GetNamesByDateRequest();
            inValue.Body = new Deceased2010Client.Deceased2010Service.GetNamesByDateRequestBody();
            inValue.Body.dateinput = dateinput;
            Deceased2010Client.Deceased2010Service.GetNamesByDateResponse retVal = ((Deceased2010Client.Deceased2010Service.Deceased2010ServiceSoap)(this)).GetNamesByDate(inValue);
            return retVal.Body.GetNamesByDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Deceased2010Client.Deceased2010Service.GetNamesByDateResponse> Deceased2010Client.Deceased2010Service.Deceased2010ServiceSoap.GetNamesByDateAsync(Deceased2010Client.Deceased2010Service.GetNamesByDateRequest request) {
            return base.Channel.GetNamesByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Deceased2010Client.Deceased2010Service.GetNamesByDateResponse> GetNamesByDateAsync(string dateinput) {
            Deceased2010Client.Deceased2010Service.GetNamesByDateRequest inValue = new Deceased2010Client.Deceased2010Service.GetNamesByDateRequest();
            inValue.Body = new Deceased2010Client.Deceased2010Service.GetNamesByDateRequestBody();
            inValue.Body.dateinput = dateinput;
            return ((Deceased2010Client.Deceased2010Service.Deceased2010ServiceSoap)(this)).GetNamesByDateAsync(inValue);
        }
    }
}
